{{- if .Values.datadog.metrics.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-datadog-{{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "service.fullname" . }}-secrets
  data:
  - secretKey: apiKey
    remoteRef:
      {{- if and .Values.datadog.metrics.enabled .Values.datadog.metrics.apiKeySecret }}
      key: {{ .Values.datadog.metrics.apiKeySecret }}
      {{- end }}
      property: api-key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}
