{{- if .Values.flink.mysql.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-mysql-{{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "service.fullname" . }}-secrets
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.flink.mysql.smSecret }}
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}