{{- if or .Values.datadog.metrics.enabled .Values.flink.mysql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountNameSM" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountSM.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
